# Generated by Django 6.1 on 2026-09-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['expires_at', 'status'], name='marketplace_expires_b5d18d_idx'),
        ),
    ]
